trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - inspari/logging/**
      - test/** 
      - azure-pipelines-test.yml

variables:
- group: INSPARI # Variable group containing GIT_TOKEN secret

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-24.04'
  strategy:
    matrix:
      Python313:
        python.version: '3.13'
    maxParallel: 2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: |
      export POETRY_HTTP_BASIC_INSPARI_CONFIG_USERNAME=emer
      export POETRY_HTTP_BASIC_INSPARI_CONFIG_PASSWORD=$(INSPARI_CONFIG_PAT_TOKEN)
      echo $(INSPARI_CONFIG_PAT_TOKEN)
      pipx install poetry
      poetry install -E azure --no-root
    displayName: 'Install dependencies'
  - script: |
      pip install pytest-azurepipelines
      poetry run coverage run -m pytest --junitxml=results.xml
      poetry run coverage xml -o coverage.xml
    displayName: 'Run Unit Tests with pytest'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results.xml'
      testRunTitle: 'Python $(python.version)'
      condition: succeededOrFailed()
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '**/coverage.xml'
