trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - inspari/logging/**
      - test/** 
      - azure-pipeline-test.yml
      - pyproject.toml
      - poetry.lock

variables:
- group: INSPARI # Variable group containing GIT_TOKEN secret

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-24.04'
  strategy:
    matrix:
      Python313:
        python.version: '3.13'
    maxParallel: 2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: |
      curl -sSL https://install.python-poetry.org | python3 -
      poetry config repositories.inspari-config https://Inspari-Accelerators@dev.azure.com/Inspari-Accelerators/Accelerators/_git/inspari-config
      poetry config http-basic.inspari-config $(INSPARI_CONFIG_PAT_USERNAME) $(INSPARI_CONFIG_PAT_TOKEN)
      poetry env use python3
      git config --global url."https://Inspari-Accelerators@dev.azure.com/Inspari-Accelerators/Accelerators/_git/inspari-config".insteadOf git@ssh.dev.azure.com:v3/Inspari-Accelerators/Accelerators/inspari-config
      poetry install -E azure
      git config --global url."https://Inspari-Accelerators@dev.azure.com/Inspari-Accelerators/Accelerators/_git/inspari-config".insteadOf git@ssh.dev.azure.com:v3/Inspari-Accelerators/Accelerators/inspari-config
      poetry install -E azure
    displayName: 'Install dependencies'
  - script: |
      pip install pytest-azurepipelines
      poetry run coverage run -m pytest --junitxml=results.xml
      poetry run coverage xml -o coverage.xml
    displayName: 'Run Unit Tests with pytest'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results.xml'
      testRunTitle: 'Python $(python.version)'
      condition: succeededOrFailed()
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '**/coverage.xml'